---
version: 0.2
env:
  variables:
    DOCKER_IMAGE: "${AWS_ACCOUNT_ID}.dkr.ecr.$AWS_REGION.amazonaws.com/test/node-server:latest"
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      # initialize Docker daemon
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - echo $DOCKER_IMAGE_REPO_ARN
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t test/node-server ."
      - "docker tag test/node-server $DOCKER_IMAGE_REPO_ARN"
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - echo $AWS_ACCOUNT_ID
      - echo $AWS_REGION
      # - "docker push bizm/node-server:latest"
      # - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/test/node-server:latest
      - docker push $DOCKER_IMAGE_REPO_ARN
