---
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t bizm/node-server ."
      - "docker tag bizm/node-server bizm/node-server:latest"
  post_build:
    commands:
      - "echo Build completed on `date`"
      # - "echo Pushing the Docker image..."
      # - "docker push bizm/node-server:latest"
version: 0.2
