---
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      # initialize Docker daemon
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t bizm/node-server ."
      - "docker tag bizm/node-server bizm/node-server:latest"
  post_build:
    commands:
      - "echo Build completed on `date`"
      # - "echo Pushing the Docker image..."
      # - "docker push bizm/node-server:latest"
version: 0.2
