---
AWSTemplateFormatVersion: 2010-09-09
Description: "Test CloudFormation template for CodeBuild"

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: node-server-codebuild-test-cf
      Artifacts:
        Type: NO_ARTIFACTS
      Source:
        Type: GITHUB
        Auth:
          # ???
          # Resource: "{{resolve:secretsmanager:CICD:SecretString:GitHubAccessToken}}"
          Type: OAUTH
        BuildSpec: buildspec.yml
        Location: https://github.com/bizm/fargate-node-server.git
      SourceVersion: master
      ServiceRole: arn:aws:iam::115162817961:role/service-role/codeBuildRole

      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        # Image: aws/codebuild/amazonlinux2-x86_64-standard:1.0
        Image: aws/codebuild/standard:2.0-1.13.0
        PrivilegedMode: true
